#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

ARG sdk_vsn=1.13.0

FROM digitalasset/daml-sdk:${sdk_vsn} AS hunter

WORKDIR /home/daml/

COPY daml.yaml .
COPY daml ./daml

FROM hunter

EXPOSE 6865
EXPOSE 7500

ENTRYPOINT daml start \
  --sandbox-option="--address=0.0.0.0" \
  --sandbox-port 6865 \
  --open-browser=no \
  --json-api-port=none
